// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Db.MinFinInv.PowerTools.Models;

public partial class InvAccount
{
    public string Id { get; set; }

    public string SrcAccount { get; set; }

    public string TrgAccount { get; set; }

    public DateOnly? OpenedOn { get; set; }

    public DateOnly? ClosedOn { get; set; }

    public decimal? BalanceOpening { get; set; }

    public decimal? BalanceClosing { get; set; }

    public decimal? TotalIn { get; set; }

    public string Institution { get; set; }

    public string AcntNumber { get; set; }

    public string DfsPlanNum { get; set; }

    public string DfsClientId { get; set; }

    public string AcntType { get; set; }

    public string AcntHolder { get; set; }

    public string Advisor { get; set; }

    public string Notes { get; set; }

    public string SortableFlags { get; set; }

    public DateTime? RowAddedAt { get; set; }

    public string Note2023 { get; set; }

    public virtual ICollection<AcntHist> AcntHists { get; set; } = new List<AcntHist>();

    public virtual ICollection<InvAccount> InverseSrcAccountNavigation { get; set; } = new List<InvAccount>();

    public virtual InvAccount SrcAccountNavigation { get; set; }
}