// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Db.MinFinInv.PowerTools.Models;

public partial class VLatestAcntBalance2
{
    public string Id { get; set; }

    public string AcntNumber { get; set; }

    public string DfsPlanNum { get; set; }

    public string DfsClientId { get; set; }

    public string Institution { get; set; }

    public string AcntType { get; set; }

    public string AcntHolder { get; set; }

    public DateOnly? OpenedOn { get; set; }

    public string Notes { get; set; }

    public int? HistCnt { get; set; }

    public DateOnly? LastHist { get; set; }

    public decimal? LastBlnc { get; set; }

    public decimal? TtlTxn { get; set; }

    public decimal? TtlTxnMissing { get; set; }
}