// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Db.MinFinInv.PowerTools.Models;

public partial class VLatestAcntBalance3
{
    public string InvAccountId { get; set; }

    public DateOnly? OpenedOn { get; set; }

    public DateOnly? ClosedOn { get; set; }

    public string Src { get; set; }

    public string Trg { get; set; }

    public DateOnly? LastTxn { get; set; }

    public int? TxnCnt { get; set; }

    public int? LastTxnCnt { get; set; }

    public decimal? MinBalance { get; set; }

    public decimal? MaxBalance { get; set; }

    public decimal? LastTtlBalance { get; set; }

    public string Notes { get; set; }
}