// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Db.MinFinInv.PowerTools.Models;

public partial class VLatestGrandTotal
{
    public int? AcntQnt { get; set; }

    public decimal? TotalBalance { get; set; }
}