// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Db.MinFinInv.PowerTools.Models;

public partial class VLatestAcntBalance
{
    public string Id { get; set; }

    public string SrcAccount { get; set; }

    public DateOnly? OpenedOn { get; set; }

    public DateOnly? ClosedOn { get; set; }

    public decimal? BalanceOpening { get; set; }

    public decimal? BalanceClosing { get; set; }

    public decimal? TotalIn { get; set; }

    public string Institution { get; set; }

    public string AcntNumber { get; set; }

    public string AuxIdNumber { get; set; }

    public string DfsPlanNum { get; set; }

    public string DfsClientId { get; set; }

    public string AcntType { get; set; }

    public string AcntHolder { get; set; }

    public string Advisor { get; set; }

    public string Notes { get; set; }

    public DateOnly Date { get; set; }

    public decimal? Txn { get; set; }

    public decimal? TotalInvested { get; set; }

    public decimal? Balance { get; set; }

    public decimal? UnitValue { get; set; }

    public decimal? BalanceInUnits { get; set; }

    public string NotesHist { get; set; }
}