namespace WpfUserControlLib.Converters;

public readonly record struct AreaCode(string Code, string Area, int Prio, string Oset, string Note)
{
  public string Tooltip => $"\t{Area,12}    {Oset} h  \n{Note}";
}

public static class AreaCodeValidator
{
  static readonly AreaCode[] _areaCodes;
  static AreaCodeValidator() => _areaCodes = new[]
    {
      new ("5255", "MX", 9, "-6", "Mexico: Mexico City area (country code + city code)"),
      new ("201", "NJ", 9, "-5", "N New Jersey: Jersey City, Hackensack (see split 973, overlay 551)"),
      new ("202", "DC", 9, "-5", "Washington, D.C."),
      new ("203", "CT", 9, "-5", "Connecticut: Fairfield County and New Haven County; Bridgeport, New Haven (see 860)"),
      new ("204", "MB", 6, "-6", "Canada: Manitoba (see overlay 431)"),
      new ("205", "AL", 9, "-6", "Central Alabama (including Birmingham; excludes the southeastern corner of Alabama and the deep south; see splits 256 and 334)"),
      new ("206", "WA", 9, "-8", "W Washington state: Seattle and Bainbridge Island (see splits 253, 360, 425; overlay 564)"),
      new ("207", "ME", 9, "-5", "Maine"),
      new ("208", "ID", 9, "-7/-8", "Idaho"),
      new ("209", "CA", 9, "-8", "Cent. California: Stockton (see split 559)"),
      new ("210", "TX", 9, "-6", "S Texas: San Antonio (see also splits 830, 956)"),
      new ("211", "··", 9, "-■", "Local community info / referral services"),
      new ("212", "NY", 9, "-5", "New York City, New York (Manhattan; see ovelays 332, 646, 917; split 718)"),
      new ("213", "CA", 9, "-8", "S California: Los Angeles (see 310, 323, 626, 818)"),
      new ("214", "TX", 9, "-6", "Texas: Dallas Metro (overlays 469/972)"),
      new ("215", "PA", 9, "-5", "SE Pennsylvania: Philadelphia (see overlays 267)"),
      new ("216", "OH", 9, "-5", "Cleveland (see splits 330, 440)"),
      new ("217", "IL", 9, "-6", "Cent. Illinois: Springfield"),
      new ("218", "MN", 9, "-6", "N Minnesota: Duluth"),
      new ("219", "IN", 9, "-6/-5", "NW Indiana: Gary (see split 574, 260)"),
      new ("220", "OH", 9, "-5", "SE and Central Ohio (outside Columbus; overlaid on 740)"),
      new ("223", "PA", 9, "-5", "E Pennsylvania: Gettysburg, Harrisburg, Lancaster, Lebanan, and York (overlays 223, eff 8/2017)"),
      new ("224", "IL", 9, "-6", "Northern NE Illinois: Evanston, Waukegan, Northbrook (overlay on 847, eff 1/5/02)"),
      new ("225", "LA", 9, "-6", "Louisiana: Baton Rouge, New Roads, Donaldsonville, Albany, Gonzales, Greensburg, Plaquemine, Vacherie (split from 504)"),
      new ("226", "ON", 5, "-5", "Canada: SW Ontario: Windsor (overlays 519, 548)"),
      new ("228", "MS", 9, "-6", "S Mississippi (coastal areas, Biloxi, Gulfport; split from 601)"),
      new ("229", "GA", 9, "-5", "SW Georgia: Albany (split from 912; see also 478; perm 8/1/00)"),
      new ("231", "MI", 9, "-5", "W Michigan: Northwestern portion of lower Peninsula; Traverse City, Muskegon, Cheboygan, Alanson"),
      new ("234", "OH", 9, "-5", "NE Ohio: Canton, Akron (overlaid on 330; perm 10/30/00)"),
      new ("236", "BC", 8, "-8/-7", "Canada: British Columbia (see 250, 604)"),
      new ("239", "FL", 9, "-5", "Florida (Lee, Collier, and Monroe Counties, excl the Keys; see 305; eff 3/11/02; mand 3/11/03)"),
      new ("240", "MD", 9, "-5", "W Maryland: Silver Spring, Frederick, Gaithersburg (overlay, see 301)"),
      new ("242", "··", 9, "-5", "Bahamas"),
      new ("246", "··", 9, "-4", "Barbados"),
      new ("248", "MI", 9, "-5", "Michigan: Oakland County, Pontiac (split from 810; see overlay 947)"),
      new ("250", "BC", 8, "-8/-7", "Canada: British Columbia (see 236, 604)"),
      new ("251", "AL", 9, "-6", "S Alabama: Mobile and coastal areas, Jackson, Evergreen, Monroeville (split from 334, eff 6/18/01; see also 205, 256)"),
      new ("252", "NC", 9, "-5", "E North Carolina (Rocky Mount; split from 919)"),
      new ("253", "WA", 9, "-8", "Washington: South Tier - Tacoma, Federal Way (split from 206, see also 425; overlay 564)"),
      new ("254", "TX", 9, "-6", "Central Texas (Waco, Stephenville; split, see 817, 940)"),
      new ("256", "AL", 9, "-6", "E and N Alabama (Huntsville, Florence, Gadsden; split from 205; see also 334)"),
      new ("260", "IN", 9, "-5", "NE Indiana: Fort Wayne (see 219)"),
      new ("262", "WI", 9, "-6", "SE Wisconsin: counties of Kenosha, Ozaukee, Racine, Walworth, Washington, Waukesha (split from 414)"),
      new ("264", "··", 9, "-4", "Anguilla (split from 809)"),
      new ("267", "PA", 9, "-5", "SE Pennsylvania: Philadelphia (see 215)"),
      new ("268", "··", 9, "-4", "Antigua and Barbuda (split from 809)"),
      new ("269", "MI", 9, "-5", "SW Michigan: Kalamazoo, Saugatuck, Hastings, Battle Creek, Sturgis to Lake Michigan (split from 616)"),
      new ("270", "KY", 9, "-6", "W Kentucky: Bowling Green, Paducah (split from 502)"),
      new ("272", "PA", 9, "-5", "NE and N Central Pennsylvania: Wilkes-Barre, Scranton (see 717; overlaid on 570)"),
      new ("276", "VA", 9, "-5", "S and SW Virginia: Bristol, Stuart, Martinsville (split from 540; perm 9/1/01, mand 3/16/02)"),
      new ("278", "MI", 9, "-5", "Michigan (overlaid on 734, SUSPENDED)"),
      new ("281", "TX", 9, "-6", "Texas: Houston Metro (split 713; overlay 832, 346)"),
      new ("283", "OH", 9, "-5", "SW Ohio: Cincinnati (cancelled: overlaid on 513)"),
      new ("284", "··", 9, "-4", "British Virgin Islands (split from 809)"),
      new ("289", "ON", 3, "-5", "Canada: S Cent. Ontario: Greater Toronto Area ·· Durham, Halton, Hamilton-Wentworth, Niagara, Peel, York, and southern Simcoe County (excluding Toronto ·· overlaid on 905)"),
      new ("301", "MD", 9, "-5", "W Maryland: Silver Spring, Frederick, Camp Springs, Prince George's County (see 240)"),
      new ("302", "DE", 9, "-5", "Delaware"),
      new ("303", "CO", 9, "-7", "Central Colorado: Denver (see 970, also 720 overlay)"),
      new ("304", "WV", 9, "-5", "West Virginia (see overlay 681)"),
      new ("305", "FL", 9, "-5", "SE Florida: Miami, the Keys (see 786, 954; 239)"),
      new ("306", "SK", 7, "-6/-7*", "Canada: Saskatchewan (see overlay 639)"),
      new ("307", "WY", 9, "-7", "Wyoming"),
      new ("308", "NE", 9, "-6/-7", "W Nebraska: North Platte"),
      new ("309", "IL", 9, "-6", "W Cent. Illinois: Peoria"),
      new ("310", "CA", 9, "-8", "S California: Beverly Hills, West Hollywood, West Los Angeles (see split 562; overlay 424)"),
      new ("311", "··", 9, "-■", "Reserved for special applications"),
      new ("312", "IL", 9, "-6", "Illinois: Chicago (downtown only ·· in the loop; see 773; overlay 872)"),
      new ("313", "MI", 9, "-5", "Michigan: Detroit and suburbs (see 734, overlay 679)"),
      new ("314", "MO", 9, "-6", "SE Missouri: St Louis city and parts of the metro area only (see 573, 636, overlay 557)"),
      new ("315", "NY", 9, "-5", "N Cent. New York: Syracuse"),
      new ("316", "KS", 9, "-6", "S Kansas: Wichita (see split 620)"),
      new ("317", "IN", 9, "-5", "Cent. Indiana: Indianapolis (see 765)"),
      new ("318", "LA", 9, "-6", "N Louisiana: Shreveport, Ruston, Monroe, Alexandria (see split 337)"),
      new ("319", "IA", 9, "-6", "E Iowa: Cedar Rapids (see split 563)"),
      new ("320", "MN", 9, "-6", "Cent. Minnesota: Saint Cloud (rural Minn, excl St. Paul/Minneapolis)"),
      new ("321", "FL", 9, "-5", "Florida: Brevard County, Cape Canaveral area; Metro Orlando (split from 407)"),
      new ("323", "CA", 9, "-8", "S California: Los Angeles (outside downtown: Hollywood; split from 213)"),
      new ("325", "TX", 9, "-6", "Central Texas: Abilene, Sweetwater, Snyder, San Angelo (split from 915)"),
      new ("330", "OH", 9, "-5", "NE Ohio: Akron, Canton, Youngstown; Mahoning County, parts of Trumbull/Warren counties (see splits 216, 440, overlay 234)"),
      new ("331", "IL", 9, "-6", "W NE Illinois, western suburbs of Chicago (part of what used to be 708; overlaid on 630; eff 7/07)"),
      new ("332", "NY", 9, "-5", "New York City, New York (Manhattan; overlaid on 212, 646, 917)"),
      new ("334", "AL", 9, "-6", "S Alabama: Auburn/Opelika, Montgomery and coastal areas (part of what used to be 205; see also 256, split 251)"),
      new ("336", "NC", 9, "-5", "Cent. North Carolina: Greensboro, Winston-Salem, High Point (split from 910; see overlay 743)"),
      new ("337", "LA", 9, "-6", "SW Louisiana: Lake Charles, Lafayette (see split 318)"),
      new ("339", "MA", 9, "-5", "Massachusetts: Boston suburbs, to the south and west (see splits 617, 508; overlaid on 781, eff 5/2/01)"),
      new ("340", "VI", 9, "-4*", "US Virgin Islands (see also 809)"),
      new ("341", "CA", 9, "-8", "(overlay on 510; SUSPENDED)"),
      new ("343", "ON", 5, "-5", "Canada: SE Ontario: Ottawa (overlaid on 613)"),
      new ("345", "··", 9, "-5", "Cayman Islands"),
      new ("346", "TX", 9, "-6", "Mid SE Texas: central Houston (overlaid on 713, 281, and 832)"),
      new ("347", "NY", 9, "-5", "New York City, New York (overlay for 718: NYC area, except Manhattan)"),
      new ("351", "MA", 9, "-5", "Massachusetts: north of Boston to NH, 508, and 781 (overlaid on 978, eff 4/2/01)"),
      new ("352", "FL", 9, "-5", "Florida: Gainesville area, Ocala, Crystal River (split from 904)"),
      new ("360", "WA", 9, "-8", "W Washington State: Olympia, Bellingham (area circling 206, 253, and 425; split from 206; see overlay 564)"),
      new ("361", "TX", 9, "-6", "S Texas: Corpus Christi (split from 512; eff 2/13/99)"),
      new ("365", "ON", 3, "-5", "Canada: S Cent. Ontario: Greater Toronto Area ·· Durham, Halton, Hamilton-Wentworth, Niagara, Peel, York, and southern Simcoe County (overlaid on 905)"),
      new ("369", "CA", 9, "-8", "Solano County (perm 12/2/00, mand 6/2/01)"),
      new ("380", "OH", 9, "-5", "Ohio: Columbus (overlaid on 614; assigned but not in use)"),
      new ("385", "UT", 9, "-7", "Utah: Salt Lake City Metro (split from 801, eff 3/30/02 POSTPONED; see also 435)"),
      new ("386", "FL", 9, "-5", "N central Florida: Lake City (split from 904, perm 2/15/01, mand 11/5/01)"),
      new ("401", "RI", 9, "-5", "Rhode Island"),
      new ("402", "NE", 9, "-6", "E Nebraska: Omaha, Lincoln"),
      new ("403", "AB", 7, "-7", "Canada: Southern Alberta (see 587, 780, 825, 867)"),
      new ("404", "GA", 9, "-5", "N Georgia: Atlanta and suburbs (see overlay 678, split 770)"),
      new ("405", "OK", 9, "-6", "W Oklahoma: Oklahoma City (see 580)"),
      new ("406", "MT", 9, "-7", "Montana"),
      new ("407", "FL", 9, "-5", "Central Florida: Metro Orlando (see overlay 689, eff 7/02; split 321)"),
      new ("408", "CA", 9, "-8", "Cent. Coastal California: San Jose (see overlay 669)"),
      new ("409", "TX", 9, "-6", "SE Texas: Galveston, Port Arthur, Beaumont (splits 936, 979)"),
      new ("410", "MD", 9, "-5", "E Maryland: Baltimore, Annapolis, Chesapeake Bay area, Ocean City (see overlays 443, 667)"),
      new ("411", "··", 9, "-■", "Reserved for special applications"),
      new ("412", "PA", 9, "-5", "W Pennsylvania: Pittsburgh (see split 724, overlay 878)"),
      new ("413", "MA", 9, "-5", "W Massachusetts: Springfield"),
      new ("414", "WI", 9, "-6", "SE Wisconsin: Milwaukee County (see splits 920, 262)"),
      new ("415", "CA", 9, "-8", "California: San Francisco County and Marin County on the north side of the Golden Gate Bridge, extending north to Sonoma County (see 650 split; 628 overlay, eff 2/2015)"),
      new ("416", "ON", 1, "-5", "Canada: S Cent. Ontario: Toronto (see overlays 437, 647)"),
      new ("417", "MO", 9, "-6", "SW Missouri: Springfield"),
      new ("418", "QC", 4, "-5/-4", "Canada: NE Quebec: Quebec (see overlay 581)"),
      new ("419", "OH", 9, "-5", "NW Ohio: Toledo (see overlay 567, perm 1/1/02)"),
      new ("423", "TN", 9, "-5", "E Tennessee, except Knoxville metro area: Chattanooga, Bristol, Johnson City, Kingsport, Greeneville (see split 865; part of what used to be 615)"),
      new ("424", "CA", 9, "-8", "S California: Los Angeles (see split 562; overlaid on 310 mand 7/26/06)"),
      new ("425", "WA", 9, "-8", "Washington: North Tier - Everett, Bellevue (split from 206, see also 253; overlay 564)"),
      new ("430", "TX", 9, "-6", "NE Texas: Tyler (overlaid on 903, eff 7/20/02)"),
      new ("431", "MB", 6, "-6", "Canada: Manitoba (overlaid on 204; eff 11/12)"),
      new ("432", "TX", 9, "-7/-6", "W Texas: Big Spring, Midland, Odessa (split from 915, eff 4/5/03)"),
      new ("434", "VA", 9, "-5", "E Virginia: Charlottesville, Lynchburg, Danville, South Boston, and Emporia (split from 804, eff 6/1/01; see also 757)"),
      new ("435", "UT", 9, "-7", "Rural Utah outside Salt Lake City metro (see split 801)"),
      new ("437", "ON", 1, "-5", "Canada: S Cent. Ontario: Toronto (overlaid on 416)"),
      new ("438", "QC", 5, "-5", "Canada: SW Quebec: Montreal city (overlaid on 514, [delayed until 6/06] eff 10/10/03, mand 2/7/04)"),
      new ("440", "OH", 9, "-5", "Ohio: Cleveland metro area, excluding Cleveland (split from 216, see also 330)"),
      new ("441", "··", 9, "-4", "Bermuda (part of what used to be 809)"),
      new ("442", "CA", 9, "-8", "Far north suburbs of San Diego (Oceanside, Escondido; overlaid on 760)"),
      new ("443", "MD", 9, "-5", "E Maryland: Baltimore, Annapolis, Chesapeake Bay area, Ocean City (overlaid on 410, see overlay 667)"),
      new ("450", "QC", 5, "-5/-4", "Canada: Southeastern Quebec; suburbs outside metro Montreal (see overlay 579)"),
      new ("456", "··", 9, "-■", "Inbound International"),
      new ("458", "OR", 9, "-8/-7", "Oregon: Eugene, Medford (overlaid on 541)"),
      new ("464", "IL", 9, "-6", "Illinois: south suburbs of Chicago (see 630; overlaid on 708)"),
      new ("469", "TX", 9, "-6", "Texas: Dallas Metro (overlays 214/972)"),
      new ("470", "GA", 9, "-5", "Georgia: Greater Atlanta Metropolitan Area (overlaid on 404/770/678; mand 9/2/01)"),
      new ("473", "··", 9, "-4", "Grenada ('new' ·· split from 809)"),
      new ("475", "CT", 9, "-5", "Connecticut: New Haven, Greenwich, southwestern (postponed; was perm 1/6/01; mand 3/1/01???)"),
      new ("478", "GA", 9, "-5", "Central Georgia: Macon (split from 912; see also 229; perm 8/1/00; mand 8/1/01)"),
      new ("479", "AR", 9, "-6", "NW Arkansas: Fort Smith, Fayetteville, Springdale, Bentonville (SPLIt from 501, perm 1/19/02, mand 7/20/02)"),
      new ("480", "AZ", 9, "-7*", "Arizona: East Phoenix (see 520; also Phoenix split 602, 623)"),
      new ("481", "QC", 5, "-5/-4", "Canada: NE Quebec: Quebec (see overlay 418)"),
      new ("484", "PA", 9, "-5", "SE Pennsylvania: Allentown, Bethlehem, Reading, West Chester, Norristown (see 610)"),
      new ("500", "··", 9, "-■", "Personal Communication Service"),
      new ("501", "AR", 9, "-6", "Central Arkansas: Little Rock, Hot Springs, Conway (see split 479)"),
      new ("502", "KY", 9, "-5", "N Central Kentucky: Louisville (see 270)"),
      new ("503", "OR", 9, "-8", "Oregon (see 458, 541, 971)"),
      new ("504", "LA", 9, "-6", "E Louisiana: New Orleans metro area (see splits 225, 985)"),
      new ("505", "NM", 9, "-7", "North central and northwestern New Mexico (Albuquerque, Santa Fe, Los Alamos; see split 575, eff 10/07/07)"),
      new ("506", "NB", 6, "-4", "Canada: New Brunswick"),
      new ("507", "MN", 9, "-6", "S Minnesota: Rochester, Mankato, Worthington"),
      new ("508", "MA", 9, "-5", "Cent. Massachusetts: Framingham; Cape Cod (see split 978, overlay 774)"),
      new ("509", "WA", 9, "-8", "E and Central Washington state: Spokane, Yakima, Walla Walla, Ellensburg"),
      new ("510", "CA", 9, "-8", "California: Oakland, East Bay (see 925)"),
      new ("511", "··", 9, "-■", "Nationwide travel information"),
      new ("512", "TX", 9, "-6", "S Texas: Austin (see split 361; overlay 737, perm 11/10/01)"),
      new ("513", "OH", 9, "-5", "SW Ohio: Cincinnati (see split 937; overlay 283 cancelled)"),
      new ("514", "QC", 5, "-5", "Canada: SW Quebec: Montreal city (see overlay 438, eff 10/10/03, mand 2/7/04)"),
      new ("515", "IA", 9, "-6", "Cent. Iowa: Des Moines (see split 641)"),
      new ("516", "NY", 9, "-5", "New York: Nassau County, Long Island; Hempstead (see split 631)"),
      new ("517", "MI", 9, "-5", "Cent. Michigan: Lansing (see split 989)"),
      new ("518", "NY", 9, "-5", "NE New York: Albany"),
      new ("519", "ON", 5, "-5", "Canada: SW Ontario: Windsor (see overlay 226, 548)"),
      new ("520", "AZ", 9, "-7*", "SE Arizona: Tucson area (split from 602; see split 928)"),
      new ("530", "CA", 9, "-8", "NE California: Eldorado County area, excluding Eldorado Hills itself: incl cities of Auburn, Chico, Redding, So. Lake Tahoe, Marysville, Nevada City/Grass Valley (split from 916)"),
      new ("539", "OK", 9, "-6", "E Oklahoma: Tulsa area (overlaid on 918)"),
      new ("540", "VA", 9, "-5", "Western and Southwest Virginia: Shenandoah and Roanoke valleys: Fredericksburg, Harrisonburg, Roanoke, Salem, Lexington and nearby areas (see split 276; split from 703)"),
      new ("541", "OR", 9, "-8/-7", "Oregon: Eugene, Medford (split from 503; 503 retains NW part [Portland/Salem], all else moves to 541; eastern oregon is UTC-7). Also serves small part of northern California (NE corner of Del Norte County). (See overlay 458.)"),
      new ("548", "ON", 5, "-5", "Canada: Southwestern Ontario (London, Sarnia, Kitchener-Waterloo and Brantford; overlaid on 226, 519)"),
      new ("551", "NJ", 9, "-5", "N New Jersey: Jersey City, Hackensack (overlaid on 201)"),
      new ("555", "··", 9, "?", "Reserved for directory assistance applications"),
      new ("557", "MO", 9, "-6", "SE Missouri: St Louis metro area only (cancelled: overlaid on 314)"),
      new ("559", "CA", 9, "-8", "Central California: Fresno (split from 209)"),
      new ("561", "FL", 9, "-5", "S. Central Florida: Palm Beach County (West Palm Beach, Boca Raton, Vero Beach; see split 772, eff 2/11/02; mand 11/11/02)"),
      new ("562", "CA", 9, "-8", "California: Long Beach (split from 310 Los Angeles)"),
      new ("563", "IA", 9, "-6", "E Iowa: Davenport, Dubuque (split from 319, eff 3/25/01)"),
      new ("564", "WA", 9, "-8", "W Washington State: Olympia, Bellingham (overlaid on 360; see also 206, 253, 425; assigned but not in use)"),
      new ("567", "OH", 9, "-5", "NW Ohio: Toledo (overlaid on 419, perm 1/1/02)"),
      new ("570", "PA", 9, "-5", "NE and N Central Pennsylvania: Wilkes-Barre, Scranton (see 717; see overlay 272)"),
      new ("571", "VA", 9, "-5", "Northern Virginia: Arlington, McLean, Tysons Corner (to be overlaid on 703 3/1/00; see earlier split 540)"),
      new ("573", "MO", 9, "-6", "SE Missouri: excluding St Louis metro area, includes Central/East Missouri, area between St. Louis and Kansas City"),
      new ("574", "IN", 9, "-5", "N Indiana: Elkhart, South Bend (split from 219)"),
      new ("575", "NM", 9, "-7", "New Mexico (Las Cruces, Alamogordo, Roswell; split from 505, eff 10/07/07)"),
      new ("579", "QC", 5, "-5/-4", "Canada: Southeastern Quebec; suburbs outside metro Montreal (overlaid on 450)"),
      new ("580", "OK", 9, "-6", "W Oklahoma (rural areas outside Oklahoma City; split from 405)"),
      new ("581", "QC", 5, "-5/-4", "Canada: NE Quebec: Quebec (overlaid on 418)"),
      new ("585", "NY", 9, "-5", "NW New York: Rochester (split from 716)"),
      new ("586", "MI", 9, "-5", "Michigan: Macomb County (split from 810; perm 9/22/01, mand 3/23/02)"),
      new ("587", "AB", 7, "-7", "Canada: Alberta (see 403, 780, 825)"),
      new ("600", "··", 9, "-■", "Canadian Services"),
      new ("601", "MS", 9, "-6", "Mississippi: Meridian, Jackson area (see splits 228, 662; overlay 769)"),
      new ("602", "AZ", 9, "-7*", "Arizona: Phoenix (see 520; also Phoenix split 480, 623)"),
      new ("603", "NH", 9, "-5", "New Hampshire"),
      new ("604", "BC", 8, "-8", "Canada: British Columbia: Greater Vancouver (overlay 778, perm 11/3/01; see 250)"),
      new ("605", "SD", 9, "-6/-7", "South Dakota"),
      new ("606", "KY", 9, "-5/-6", "E Kentucky: area east of Frankfort: Ashland (see 859)"),
      new ("607", "NY", 9, "-5", "S Cent. New York: Ithaca, Binghamton; Catskills"),
      new ("608", "WI", 9, "-6", "SW Wisconsin: Madison"),
      new ("609", "NJ", 9, "-5", "S New Jersey: Trenton (see 856)"),
      new ("610", "PA", 9, "-5", "SE Pennsylvania: Allentown, Bethlehem, Reading, West Chester, Norristown (see overlays 484, 835)"),
      new ("611", "··", 9, "-■", "Reserved for special applications"),
      new ("612", "MN", 9, "-6", "Cent. Minnesota: Minneapolis (split from St. Paul, see 651; see splits 763, 952)"),
      new ("613", "ON", 5, "-5", "Canada: SE Ontario: Ottawa (see overlay 343)"),
      new ("614", "OH", 9, "-5", "SE Ohio: Columbus (see overlay 380)"),
      new ("615", "TN", 9, "-6", "Northern Middle Tennessee: Nashville metro area (see 423, 931; see overlay 629, eff 2014)"),
      new ("616", "MI", 9, "-5", "W Michigan: Holland, Grand Haven, Greenville, Grand Rapids, Ionia (see split 269)"),
      new ("617", "MA", 9, "-5", "Massachusetts: greater Boston (see overlay 857)"),
      new ("618", "IL", 9, "-6", "S Illinois: Centralia"),
      new ("619", "CA", 9, "-8", "S California: San Diego (see split 760; overlay 858, 935)"),
      new ("620", "KS", 9, "-6", "S Kansas: Wichita (split from 316; perm 2/3/01)"),
      new ("623", "AZ", 9, "-7*", "Arizona: West Phoenix (see 520; also Phoenix split 480, 602)"),
      new ("626", "CA", 9, "-8", "E S California: Pasadena (split from 818 Los Angeles)"),
      new ("627", "CA", 9, "-8", "No longer in use [was Napa, Sonoma counties (perm 10/13/01, mand 4/13/02); now 707]"),
      new ("628", "CA", 9, "-8", "California: San Francisco County and Marin County on the north side of the Golden Gate Bridge, extending north to Sonoma County (overlaid on 415, eff 2/2015)"),
      new ("629", "TN", 9, "-6", "Northern Middle Tennessee: Nashville metro area (see 423, 931; overlaid on 615, eff 2014)"),
      new ("630", "IL", 9, "-6", "W NE Illinois, western suburbs of Chicago (part of what used to be 708; overlay 331)"),
      new ("631", "NY", 9, "-5", "New York: Suffolk County, Long Island; Huntington, Riverhead (split 516)"),
      new ("636", "MO", 9, "-6", "Missouri: W St. Louis metro area of St. Louis county, St. Charles County, Jefferson County area south (between 314 and 573)"),
      new ("639", "SK", 6, "-6/-7*", "Canada: Saskatchewan (overlaid on 306)"),
      new ("641", "IA", 9, "-6", "Iowa: Mason City, Marshalltown, Creston, Ottumwa (split from 515; perm 7/9/00)"),
      new ("646", "NY", 9, "-5", "New York (overlaid on 212, 332, 917) NYC (mostly mobile)"),
      new ("647", "ON", 1, "-5", "Canada: S Cent. Ontario: Toronto (overlaid on 416)"),
      new ("649", "··", 9, "-5", "Turks & Caicos Islands"),
      new ("650", "CA", 9, "-8", "California: Peninsula south of San Francisco ·· San Mateo County, parts of Santa Clara County (split from 415)"),
      new ("651", "MN", 9, "-6", "Cent. Minnesota: St. Paul (split from Minneapolis, see 612)"),
      new ("657", "CA", 9, "-8", "Northern and western Orange County (overlaid on 714)"),
      new ("660", "MO", 9, "-6", "N Missouri (split from 816)"),
      new ("661", "CA", 9, "-8", "California: N Los Angeles, Mckittrick, Mojave, Newhall, Oildale, Palmdale, Taft, Tehachapi, Bakersfield, Earlimart, Lancaster (split from 805)"),
      new ("662", "MS", 9, "-6", "N Mississippi: Tupelo, Grenada (split from 601)"),
      new ("664", "··", 9, "-4", "Montserrat (split from 809)"),
      new ("667", "MD", 9, "-5", "E Maryland: Baltimore, Annapolis, Chesapeake Bay area, Ocean City (overlaid on 410, 443)"),
      new ("669", "CA", 9, "-8", "Cent. Coastal California: San Jose (overlaid on 408; eff 10/20/2012)"),
      new ("670", "MP", 9, "+10*", "Commonwealth of the Northern Mariana Islands (CNMI, US Commonwealth)"),
      new ("671", "GU", 9, "+10*", "Guam"),
      new ("678", "GA", 9, "-5", "N Georgia: metropolitan Atlanta (overlay; see 404, 770)"),
      new ("679", "MI", 9, "-5/-6", "Michigan: Dearborn area (overlaid on 313; assigned but not in use)"),
      new ("681", "WV", 9, "-5", "West Virginia (overlaid on 304)"),
      new ("682", "TX", 9, "-6", "Texas: Fort Worth areas (perm 10/7/00, mand 12/9/00)"),
      new ("684", "··", 9, "-11", "American Samoa"),
      new ("689", "FL", 9, "-5", "Central Florida: Metro Orlando (see overlay 321; overlaid on 407, assigned but not in use)"),
      new ("700", "··", 9, "-■", "Interexchange Carrier Services"),
      new ("701", "ND", 9, "-6", "North Dakota"),
      new ("702", "NV", 9, "-8", "S. Nevada: Clark County, incl Las Vegas (overlay 725, eff 6/2014; see also 775)"),
      new ("703", "VA", 9, "-5", "Northern Virginia: Arlington, McLean, Tysons Corner (see split 540; overlay 571)"),
      new ("704", "NC", 9, "-5", "W North Carolina: Charlotte (see split 828, overlay 980)"),
      new ("705", "ON", 5, "-5", "Canada: NE Ontario: Sault Ste. Marie/N Ontario: N Bay, Sudbury"),
      new ("706", "GA", 9, "-5", "N Georgia: Columbus, Augusta (see overlay 762)"),
      new ("707", "CA", 9, "-8", "NW California: Santa Rosa, Napa, Vallejo, American Canyon, Fairfield"),
      new ("708", "IL", 9, "-6", "Illinois: southern and western suburbs of Chicago (see 630; overlay 464)"),
      new ("709", "NL", 7, "-4/-3.5", "Canada: Newfoundland and Labrador"),
      new ("710", "··", 9, "?", "US Government"),
      new ("711", "··", 9, "-■", "Telecommunications Relay Services"),
      new ("712", "IA", 9, "-6", "W Iowa: Council Bluffs"),
      new ("713", "TX", 9, "-6", "Mid SE Texas: central Houston (split 281; overlay 346, 832)"),
      new ("714", "CA", 9, "-8", "Northern and western Orange County (see split 949, overlay 657)"),
      new ("715", "WI", 9, "-6", "N Wisconsin: Eau Claire, Wausau, Superior"),
      new ("716", "NY", 9, "-5", "NW New York: Buffalo (see split 585)"),
      new ("717", "PA", 9, "-5", "E Pennsylvania: Harrisburg (see split 570, overlay 223)"),
      new ("718", "NY", 9, "-5", "New York City, New York (Queens, Staten Island, The Bronx, and Brooklyn; also Marble Hill section of Manhattan; see split 212, 347, 929)"),
      new ("719", "CO", 9, "-7", "SE Colorado: Pueblo, Colorado Springs"),
      new ("720", "CO", 9, "-7", "Central Colorado: Denver (overlaid on 303)"),
      new ("721", "··", 9, "-4", "Sint Maarten (used to be country code +599)"),
      new ("724", "PA", 9, "-5", "SW Pennsylvania (areas outside metro Pittsburgh; split from 412)"),
      new ("725", "NV", 9, "-8", "S. Nevada: Clark County, incl Las Vegas (overlaid on 702, eff 6/2014; see also 775)"),
      new ("727", "FL", 9, "-5", "Florida Tampa Metro: Saint Petersburg, Clearwater (Pinellas and parts of Pasco County; split from 813)"),
      new ("731", "TN", 9, "-6", "W Tennessee: outside Memphis metro area (split from 901, perm 2/12/01, mand 9/17/01)"),
      new ("732", "NJ", 9, "-5", "Cent. New Jersey: Toms River, New Brunswick, Bound Brook (see overlay 848)"),
      new ("734", "MI", 9, "-5", "SE Michigan: west and south of Detroit ·· Ann Arbor, Monroe (split from 313)"),
      new ("737", "TX", 9, "-6", "S Texas: Austin (overlaid on 512, suspended; see also 361)"),
      new ("740", "OH", 9, "-5", "SE and Central Ohio (outside Columbus; split from 614; overlay 220)"),
      new ("743", "NC", 9, "-5", "Cent. North Carolina: Greensboro, Winston-Salem, High Point (overlaid on 336)"),
      new ("747", "CA", 9, "-8", "S California: Los Angeles, Agoura Hills, Calabasas, Hidden Hills, and Westlake Village (see 818; implementation suspended)"),
      new ("754", "FL", 9, "-5", "Florida: Broward County area, incl Ft. Lauderdale (overlaid on 954; perm 8/1/01, mand 9/1/01)"),
      new ("757", "VA", 9, "-5", "E Virginia: Tidewater / Hampton Roads area ·· Norfolk, Virginia Beach, Chesapeake, Portsmouth, Hampton, Newport News, Suffolk (part of what used to be 804)"),
      new ("758", "··", 9, "-4", "St. Lucia (split from 809)"),
      new ("760", "CA", 9, "-8", "California: San Diego North County to Sierra Nevada (split from 619; see overlay 442)"),
      new ("762", "GA", 9, "-5", "N Georgia: Columbus, Augusta (overlaid on 706)"),
      new ("763", "MN", 9, "-6", "Minnesota: Minneapolis NW (split from 612; see also 952)"),
      new ("764", "CA", 9, "-8", "(overlay on 650; SUSPENDED)"),
      new ("765", "IN", 9, "-5", "Indiana: outside Indianapolis (split from 317)"),
      new ("767", "··", 9, "-4", "Dominica (split from 809)"),
      new ("769", "MS", 9, "-6", "Mississippi: Meridian, Jackson area (overlaid on 601; perm 7/19/04, mand 3/14/05)"),
      new ("770", "GA", 9, "-5", "Georgia: Atlanta suburbs: outside of I-285 ring road (part of what used to be 404; see also overlay 678)"),
      new ("772", "FL", 9, "-5", "S. Central Florida: St. Lucie, Martin, and Indian River counties (split from 561; eff 2/11/02; mand 11/11/02)"),
      new ("773", "IL", 9, "-6", "Illinois: city of Chicago, outside the loop (see 312; overlay 872)"),
      new ("774", "MA", 9, "-5", "Cent. Massachusetts: Framingham; Cape Cod (see split 978, overlaid on 508, eff 4/2/01)"),
      new ("775", "NV", 9, "-8", "N. Nevada: Reno (all of NV except Clark County area; see 702)"),
      new ("778", "BC", 8, "-8", "Canada: British Columbia: Greater Vancouver (overlaid on 604, per 11/3/01; see also 250)"),
      new ("779", "IL", 9, "-6", "NW Illinois: Rockford, Kankakee (overlaid on 815; eff 8/19/06, mand 2/17/07)"),
      new ("780", "AB", 7, "-7", "Canada: Northern Alberta, north of Lacombe (see 403, 587, 825)"),
      new ("781", "MA", 9, "-5", "Massachusetts: Boston surburbs, to the north and west (see splits 617, 508; overlay 339)"),
      new ("782", "NS", 9, "-4", "Nova Scotia & Prince Edward Island (to be overlaid on 902, eff 11/30/14)"),
      new ("784", "··", 9, "-4", "St. Vincent & Grenadines (split from 809)"),
      new ("785", "KS", 9, "-6", "N & W Kansas: Topeka (split from 913)"),
      new ("786", "FL", 9, "-5", "SE Florida, Monroe County (Miami; overlaid on 305)"),
      new ("787", "PR", 9, "-4*", "Puerto Rico (see overlay 939, perm 8/1/01)"),
      new ("800", "··", 9, "?", "US/Canada toll free (see 888, 877, 866, 855, 844, 833, 822)"),
      new ("801", "UT", 9, "-7", "Utah: Salt Lake City Metro (see split 385, eff 3/30/02; see also split 435)"),
      new ("802", "VT", 9, "-5", "Vermont"),
      new ("803", "SC", 9, "-5", "South Carolina: Columbia, Aiken, Sumter (see 843, 864)"),
      new ("804", "VA", 9, "-5", "E Virginia: Richmond (see splits 757, 434)"),
      new ("805", "CA", 9, "-8", "S Cent. and Cent. Coastal California: Ventura County, Santa Barbara County: San Luis Obispo, Thousand Oaks, Carpinteria, Santa Barbara, Santa Maria, Lompoc, Santa Ynez Valley / Solvang (see 661 split)"),
      new ("806", "TX", 9, "-6", "Panhandle Texas: Amarillo, Lubbock"),
      new ("807", "ON", 6, "-5/-6", "Canada: W Ontario: Thunder Bay region to Manitoba border"),
      new ("808", "HI", 9, "-10*", "Hawaii"),
      new ("809", "··", 9, "-4", "Dominican Republic (see splits 264, 268, 284, 340, 441, 473, 664, 758, 767, 784, 868, 876; overlay 829)"),
      new ("810", "MI", 9, "-5", "E Michigan: Flint, Pontiac (see 248; split 586)"),
      new ("811", "··", 9, "-■", "Reserved for special applications"),
      new ("812", "IN", 9, "-6/-5", "S Indiana: Evansville, Cincinnati outskirts in IN, Columbus, Bloomington (mostly GMT-5)"),
      new ("813", "FL", 9, "-5", "SW Florida: Tampa Metro (splits 727 St. Petersburg, Clearwater, and 941 Sarasota)"),
      new ("814", "PA", 9, "-5", "Cent. Pennsylvania: Erie"),
      new ("815", "IL", 9, "-6", "NW Illinois: Rockford, Kankakee (see overlay 779; eff 8/19/06, mand 2/17/07)"),
      new ("816", "MO", 9, "-6", "N Missouri: Kansas City (see split 660, overlay 975)"),
      new ("817", "TX", 9, "-6", "N Cent. Texas: Fort Worth area (see 254, 940)"),
      new ("818", "CA", 9, "-8", "S California: Los Angeles: San Fernando Valley (see 213, 310, 562, 626, 747)"),
      new ("819", "QC", 9, "-5", "NW Quebec: Trois Rivieres, Sherbrooke, Outaouais (Gatineau, Hull), and the Laurentians (up to St Jovite / Tremblant) (see split 867; see overlay 873)"),
      new ("822", "··", 9, "?", "US/Canada toll free (proposed, may not be in use yet)"),
      new ("825", "AB", 9, "-7", "Alberta (overlay; see 403, 587, 780)"),
      new ("828", "NC", 9, "-5", "W North Carolina: Asheville (split from 704)"),
      new ("829", "··", 9, "-4", "Dominican Republic (perm 1/31/05; mand 8/1/05; overlaid on 809)"),
      new ("830", "TX", 9, "-6", "Texas: region surrounding San Antonio (split from 210)"),
      new ("831", "CA", 9, "-8", "California: central coast area from Santa Cruz through Monterey County"),
      new ("832", "TX", 9, "-6", "Texas: Houston (overlay 713, 281, 346)"),
      new ("833", "··", 9, "?", "US/Canada toll free (proposed, may not be in use yet)"),
      new ("835", "PA", 9, "-5", "SE Pennsylvania: Allentown, Bethlehem, Reading, West Chester, Norristown (overlaid on 610, eff 5/1/01; see also 484)"),
      new ("843", "SC", 9, "-5", "South Carolina, coastal area: Charleston, Beaufort, Myrtle Beach (split from 803)"),
      new ("844", "··", 9, "?", "US/Canada toll free (proposed, may not be in use yet)"),
      new ("845", "NY", 9, "-5", "New York: Poughkeepsie; Nyack, Nanuet, Valley Cottage, New City, Putnam, Dutchess, Rockland, Orange, Ulster and parts of Sullivan counties in New York's lower Hudson Valley and Delaware County in the Catskills (see 914; perm 6/5/00)"),
      new ("847", "IL", 9, "-6", "Northern NE Illinois: northwestern suburbs of chicago (Evanston, Waukegan, Northbrook; see overlay 224)"),
      new ("848", "NJ", 9, "-5", "Cent. New Jersey: Toms River, New Brunswick, Bound Brook (see overlay 732)"),
      new ("849", "··", 9, "-4", "Dominican Republic: Santo Domingo"),
      new ("850", "FL", 9, "-6/-5", "Florida panhandle, from east of Tallahassee to Pensacola (split from 904); western panhandle (Pensacola, Panama City) are UTC-6"),
      new ("855", "··", 9, "?", "US/Canada toll free"),
      new ("856", "NJ", 9, "-5", "SW New Jersey: greater Camden area, Mt Laurel (split from 609)"),
      new ("857", "MA", 9, "-5", "Massachusetts: greater Boston (overlaid on 617, eff 4/2/01)"),
      new ("858", "CA", 9, "-8", "S California: San Diego (see split 760; overlay 619, 935)"),
      new ("859", "KY", 9, "-5", "N and Central Kentucky: Lexington; suburban KY counties of Cincinnati OH metro area; Covington, Newport, Ft. Thomas, Ft. Wright, Florence (split from 606)"),
      new ("860", "CT", 9, "-5", "Connecticut: areas outside of Fairfield and New Haven Counties (split from 203, overlay 959)"),
      new ("862", "NJ", 9, "-5", "N New Jersey: Newark Paterson Morristown (overlaid on 973)"),
      new ("863", "FL", 9, "-5", "Florida: Lakeland, Polk County (split from 941)"),
      new ("864", "SC", 9, "-5", "South Carolina, upstate area: Greenville, Spartanburg (split from 803)"),
      new ("865", "TN", 9, "-5", "E Tennessee: Knoxville, Knox and adjacent counties (split from 423; part of what used to be 615)"),
      new ("866", "··", 9, "?", "US/Canada toll free"),
      new ("867", "YT", 8, "-5/-6/-7/-8", "Canada: Yukon, Northwest Territories, Nunavut (split from 403/819)"),
      new ("868", "··", 9, "-4", "Trinidad and Tobago ('new' ·· see 809)"),
      new ("869", "··", 9, "-4", "St. Kitts & Nevis"),
      new ("870", "AR", 9, "-6", "Arkansas: areas outside of west/central AR: Jonesboro, etc"),
      new ("872", "IL", 9, "-6", "Illinois: Chicago (downtown only ·· in the loop; see 773; overlaid on 312 and 773)"),
      new ("873", "QC", 9, "-5", "NW Quebec: Trois Rivieres, Sherbrooke, Outaouais (Gatineau, Hull), and the Laurentians (up to St Jovite / Tremblant) (overlaid on 819)"),
      new ("876", "··", 9, "-5", "Jamaica (split from 809)"),
      new ("877", "··", 9, "?", "US/Canada toll free"),
      new ("878", "PA", 9, "-5", "Pittsburgh, New Castle (overlaid on 412, perm 8/17/01, mand t.b.a.)"),
      new ("880", "··", 9, "-■", "Paid Toll-Free Service"),
      new ("881", "··", 9, "-■", "Paid Toll-Free Service"),
      new ("882", "··", 9, "-■", "Paid Toll-Free Service"),
      new ("888", "··", 9, "?", "US/Canada toll free"),
      new ("898", "··", 9, "?", "VoIP service"),
      new ("900", "··", 9, "?", "US toll calls ·· prices vary with the number called"),
      new ("901", "TN", 9, "-6", "W Tennessee: Memphis metro area (see 615, 931, split 731)"),
      new ("902", "NS", 6, "-4", "Canada: Nova Scotia, Prince Edward Island (see overlay 782)"),
      new ("903", "TX", 9, "-6", "NE Texas: Tyler (see overlay 430, eff 7/20/02)"),
      new ("904", "FL", 9, "-5", "N Florida: Jacksonville (see splits 352, 386, 850)"),
      new ("905", "ON", 3, "-5", "Canada: S Cent. Ontario: Greater Toronto Area ·· Durham, Halton, Hamilton-Wentworth, Niagara, Peel, York, and southern Simcoe County (excluding Toronto ·· see overlay 289, 365, splits 416, 647)"),
      new ("906", "MI", 9, "-6/-5", "Upper Peninsula Michigan: Sault Ste. Marie, Escanaba, Marquette (UTC-6 towards the WI border)"),
      new ("907", "AK", 9, "-9", "Alaska"),
      new ("908", "NJ", 9, "-5", "Cent. New Jersey: Elizabeth, Basking Ridge, Somerville, Bridgewater, Bound Brook"),
      new ("909", "CA", 9, "-8", "California: Inland empire: San Bernardino (see split 951), Riverside"),
      new ("910", "NC", 9, "-5", "S Cent. North Carolina: Fayetteville, Wilmington (see 336)"),
      new ("911", "··", 9, "-■", "Emergency"),
      new ("912", "GA", 9, "-5", "SE Georgia: Savannah (see splits 229, 478)"),
      new ("913", "KS", 9, "-6", "Kansas: Kansas City area (see 785)"),
      new ("914", "NY", 9, "-5", "S New York: Westchester County (see 845)"),
      new ("915", "TX", 9, "-7/-6", "W Texas: El Paso (see splits 325 eff 4/5/03; 432, eff 4/5/03)"),
      new ("916", "CA", 9, "-8", "NE California: Sacramento, Walnut Grove, Lincoln, Newcastle and El Dorado Hills (split to 530)"),
      new ("917", "NY", 9, "-5", "New York: New York City (cellular, see 646)"),
      new ("918", "OK", 9, "-6", "E Oklahoma: Tulsa (see overlay 539)"),
      new ("919", "NC", 9, "-5", "E North Carolina: Raleigh (see split 252, overlay 984)"),
      new ("920", "WI", 9, "-6", "NE Wisconsin: Appleton, Green Bay, Sheboygan, Fond du Lac (from Beaver Dam NE to Oshkosh, Appleton, and Door County; part of what used to be 414)"),
      new ("925", "CA", 9, "-8", "California: Contra Costa area: Antioch, Concord, Pleasanton, Walnut Creek (split from 510)"),
      new ("927", "FL", 9, "-5", "Florida: Cellular coverage in Orlando area"),
      new ("928", "AZ", 9, "-7*", "Central and Northern Arizona: Prescott, Flagstaff, Yuma (split from 520)"),
      new ("929", "NY", 9, "-5", "New York City, New York (Queens, Staten Island, The Bronx, and Brooklyn; also Marble Hill section of Manhattan; see split 212, 347, 718)"),
      new ("931", "TN", 9, "-6", "Middle Tennessee: semi-circular ring around Nashville (split from 615)"),
      new ("935", "CA", 9, "-8", "S California: San Diego (see split 760; overlay 858, 619; assigned but not in use)"),
      new ("936", "TX", 9, "-6", "SE Texas: Conroe, Lufkin, Nacogdoches, Crockett (split from 409, see also 979)"),
      new ("937", "OH", 9, "-5", "SW Ohio: Dayton (part of what used to be 513)"),
      new ("939", "PR", 9, "-4*", "Puerto Rico (overlaid on 787, perm 8/1/01)"),
      new ("940", "TX", 9, "-6", "N Cent. Texas: Denton, Wichita Falls (split from 254, 817)"),
      new ("941", "FL", 9, "-5", "SW Florida: Sarasota and Manatee counties (part of what used to be 813; see split 863)"),
      new ("947", "MI", 9, "-5/-6", "Michigan: Oakland County (overlays 248, perm 5/5/01)"),
      new ("949", "CA", 9, "-8", "California: S Coastal Orange County (split from 714)"),
      new ("951", "CA", 9, "-8", "California: W Riverside County (split from 909; eff 7/17/04)"),
      new ("952", "MN", 9, "-6", "Minnesota: Minneapolis SW, Bloomington (split from 612; see also 763)"),
      new ("954", "FL", 9, "-5", "Florida: Broward County area, incl Ft. Lauderdale (part of what used to be 305, see overlay 754)"),
      new ("956", "TX", 9, "-6", "Texas: Valley of Texas area; Harlingen, Laredo (split from 210)"),
      new ("957", "NM", 9, "-7", "New Mexico (pending; region unknown)"),
      new ("959", "CT", 9, "-5", "Connecticut: Hartford, New London (postponed; was overlaid on 860 perm 1/6/01; mand 3/1/01???)"),
      new ("970", "CO", 9, "-7", "N and W Colorado (part of what used to be 303)"),
      new ("971", "OR", 9, "-8", "Oregon: Metropolitan Portland, Salem/Keizer area, incl Cricket Wireless (see 503; perm 10/1/00)"),
      new ("972", "TX", 9, "-6", "Texas: Dallas Metro (overlays 214/469)"),
      new ("973", "NJ", 9, "-5", "N New Jersey: Newark, Paterson, Morristown (see overlay 862; split from 201)"),
      new ("975", "MO", 9, "-6", "N Missouri: Kansas City (overlaid on 816)"),
      new ("976", "··", 9, "-■", "Unassigned"),
      new ("978", "MA", 9, "-5", "Massachusetts: north of Boston to NH (see split 978 ·· this is the northern half of old 508; see overlay 351)"),
      new ("979", "TX", 9, "-6", "SE Texas: Bryan, College Station, Bay City (split from 409, see also 936)"),
      new ("980", "NC", 9, "-5", "North Carolina: (overlay on 704; perm 5/1/00, mand 3/15/01)"),
      new ("984", "NC", 9, "-5", "E North Carolina: Raleigh (overlaid on 919, perm 8/1/01, mand 2/5/02 POSTPONED)"),
      new ("985", "LA", 9, "-6", "E Louisiana: SE/N shore of Lake Pontchartrain: Hammond, Slidell, Covington, Amite, Kentwood, area SW of New Orleans, Houma, Thibodaux, Morgan City (split from 504; perm 2/12/01; mand 10/22/01)"),
      new ("989", "MI", 9, "-5", "Upper central Michigan: Mt Pleasant, Saginaw (split from 517; perm 4/7/01)"),
      new AreaCode("999", "··", 9, "-■", "Often used by carriers to indicate that the area code information is unavailable for CNID, even though the rest of the number is present")
    };

  public static bool Any(string phoneNumber) => _areaCodes.Any(r => phoneNumber.StartsWith(r.Code));
  public static AreaCode? FirstOrDefault(string phoneNumber) => _areaCodes.FirstOrDefault(r => phoneNumber.StartsWith(r.Code));
  public static string GetToolTip(string phoneNumber) => FirstOrDefault(phoneNumber)?.Tooltip ?? "~N/A";
}