global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using PhoneAreaCoder;
global using StandardContractsLib;
global using StandardLib.Extensions;
global using StandardLib.Helpers;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Data;
global using System.Diagnostics;
//obal using System.Drawing;  Error	CS0104	'Brush' is an ambiguous reference between 'System.Drawing.Brush' and 'System.Windows.Media.Brush'	
global using System.Globalization;
//global using System.Windows.Shapes; 
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Controls.Primitives;
global using System.Windows.Data;
global using System.Windows.Documents;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Markup;
global using System.Windows.Media;
global using System.Windows.Media.Animation;
global using System.Windows.Threading;
global using WpfUserControlLib.Extensions;
global using WpfUserControlLib.Services;
global using WpfUserControlLib.Views;
//global using StandardContractsLib;
//obal using System.Text.Json; //tu: new and very performant Json lib (Dec 2021)
global using static System.Diagnostics.Trace;
global using static System.Media.SystemSounds;
